import {
  ArrowUpDown,
  Ban,
  BarChart3,
  Bot,
  Boxes,
  Briefcase,
  Building2,
  Cake,
  CalendarClock,
  Crown,
  FileText,
  Gift,
  Home,
  LayoutTemplate,
  Layers,
  LifeBuoy,
  MessageCircle,
  MessagesSquare,
  Megaphone,
  MoonStar,
  PackageCheck,
  Palette,
  PieChart,
  PlugZap,
  QrCode,
  Receipt,
  Repeat,
  ScanLine,
  ShoppingBag,
  ShoppingCart,
  Star,
  Stethoscope,
  Store,
  Tags,
  Timer,
  Truck,
  UserCog,
  Users,
  UtensilsCrossed,
  Wallet,
  Workflow,
  Zap,
  type LucideProps,
} from "lucide-react";

const icons = {
  inbox: MessagesSquare,
  bot: Bot,
  zap: Zap,
  megaphone: Megaphone,
  template: LayoutTemplate,
  comment: MessageCircle,
  tags: Tags,
  users: Users,
  chart: BarChart3,
  swap: ArrowUpDown,
  store: Store,
  package: PackageCheck,
  cart: ShoppingCart,
  truck: Truck,
  moon: MoonStar,
  ban: Ban,
  crown: Crown,
  qr: QrCode,
  star: Star,
  gift: Gift,
  wallet: Wallet,
  receipt: Receipt,
  repeat: Repeat,
  cake: Cake,
  scan: ScanLine,
  pie: PieChart,
  building: Building2,
  briefcase: Briefcase,
  food: UtensilsCrossed,
  clinic: Stethoscope,
  bag: ShoppingBag,
  home: Home,
  boxes: Boxes,
  calendar: CalendarClock,
  support: LifeBuoy,
  workflow: Workflow,
  layers: Layers,
  file: FileText,
  timer: Timer,
  usercog: UserCog,
  plug: PlugZap,
  palette: Palette,
} as const;

export type IconName = keyof typeof icons;

export function Icon({ name, ...props }: { name: IconName } & LucideProps) {
  const Cmp = icons[name];
  return <Cmp aria-hidden {...props} />;
}
